global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'parking-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gateway:8080']
        labels:
          application: 'parking-gateway'
  
  - job_name: 'parking-uc'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8085']
        labels:
          application: 'parking-uc'
  
  - job_name: 'parking-payment'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8082']
        labels:
          application: 'parking-payment'
  
  - job_name: 'parking-vehicle'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8083']
        labels:
          application: 'parking-vehicle'
  
  - job_name: 'parking-barrier'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']
        labels:
          application: 'parking-barrier'
  
  - job_name: 'parking-space'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8086']
        labels:
          application: 'parking-space'
  
  - job_name: 'parking-report'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8084']
        labels:
          application: 'parking-report'
  
  - job_name: 'parking-oss'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8087']
        labels:
          application: 'parking-oss'
  
  - job_name: 'parking-invoice'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8088']
        labels:
          application: 'parking-invoice'
  
  - job_name: 'parking-monitor'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8089']
        labels:
          application: 'parking-monitor'
  
  - job_name: 'parking-tenant'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8090']
        labels:
          application: 'parking-tenant'
